# Generated by Django 2.1.2 on 2018-10-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181012_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishedAt',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='urltoimage',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
